### ISSUE TITLE
Add ability to paste using an API

### ISSUE THREAD

**Issue by AchoArnold** [WardPearce/paaster#130]
Hello can I create a new paste using an API

I really I can encrypt the content and generate the client secret on my end then I'll use the API to POST the encrypted secret.

Thanks

**Comment by AchoArnold** [comment]
I found the API docs

**Comment by WardPearce** [comment]
Paaster CLI tool is a simple example of our API.
https://github.com/WardPearce/paaster-cli/blob/main/paaster_cli/__init__.py#L77
