### ISSUE TITLE
Display line number

### ISSUE THREAD

**Issue by i10s** [WardPearce/paaster#15]

**Comment by WardPearce** [comment]
Appears the standard [[highlightjs-line-numbers.js](https://github.com/wcoder/highlightjs-line-numbers.js)](https://github.com/wcoder/highlightjs-line-numbers.js/) plugin won't play well with `svelte-highlight`.

Most likely will require something custom.

**Comment by i10s** [comment]
what about this? https://github.com/latex-lineno/lineno

**Comment by i10s** [comment]
I remember something about a linenos flag option, https://www.sphinx-doc.org/en/1.4.9/markup/code.html
