### ISSUE TITLE
Shortened URL

### ISSUE THREAD

**Issue by quyleanh** [WardPearce/paaster#16]
I would like to suggest the shortened url when sharing or moving text from one to other devices.
Thank you.

**Comment by WardPearce** [comment]
Thanks for your suggestion, currently self hosted version can adjust the nano ID length [here](https://github.com/WardPearce/paaster/blob/Development/docker-compose.yml#L15)

Shortening the entire URL, isn't very doable without exposing the secret key to the server. We could shorten the length of the secret but that would also increase the risk of bad actors decrypting your pastes.
