### ISSUE TITLE
Hosting on cloudflare workers ?

### ISSUE THREAD

**Issue by Jrchintu** [WardPearce/paaster#17]
Is there any plan to make it easy to host this project on cloudflare workers ? Some other pastebin such as https://github.com/SharzyL/pastebin-worker can be hosted there, but that is not encrypted. Looking forward for this idea. Thanks

**Comment by WardPearce** [comment]
Personally I don't use CF often & try to avoid the service due to privacy concerns. But if someone submits a pull request integrating this I wouldn't be against it.
