### ISSUE TITLE
Object Store Alternatives

### ISSUE THREAD

**Issue by legout** [WardPearce/paaster#197]
Cloudflare R2 offers 10GB for free.
Storj offers 150GB for free.

**Comment by WardPearce** [comment]
Hey, would love to add some additional suggestions. Please open a PR request.

Also I couldn't find any mention about Storj giving 150GB free, only 25GB free.

**Comment by legout** [comment]
It seems that Storj reduced its free offer. :-(

I´ve tested different providers.

 - Blackblaze: Cheap, and no egress if you route your traffic through cloudflares CDN. Otherwise egress can increase costs by a lot. Free tier of 10GB
 - Wasabi: Cheap, $5.99 per TB/month. But monthly download size must be below storage size. No free tier. But free for 30 days.
 - Storj: ~~150 GB~~25GB free tier, but very slow sometimes.
 - Contabo object storage:  2,49€ per 250GB/month and absolutely no additional costs. Good performance.
 - Cloudflare R2: by far the fastest. No egress but additional costs for operations. Free tier of 10GB.

I choose R2 for it´s reasonable costs and especially for its speed. In my own benchmarks, R2 was up to 5 times faster in reading and writing. All the others were very similar, expect storj which was really slow sometimes.

**Comment by WardPearce** [comment]
Please open a PR request adding these changes.

**Comment by WardPearce** [comment]
Resolved via https://github.com/WardPearce/paaster/pull/205
