### ISSUE TITLE
now that I've inadvertantly had you kinda gloss over a cli interface is there a way you would curl text to this?

### ISSUE THREAD

**Issue by Leopere** [WardPearce/paaster#228]
I'd really love some kind of example on how to send text logs or otherwise to this thing and have it spit out a url that I can send to people.

**Comment by Leopere** [comment]
I ask about curl because often that has a platform compatible binary and I don't want you to have to cross compile your cli tool for every god damn thing on the planet.

**Comment by WardPearce** [comment]
Hey. I tend to only do 1 issue per issue.
I terms of uploading a paste via curl, this isn't possible due to the E2EE nature of Paaster without some sort of Python/Bash script.

It would be possible to modify Paaster to allow piping of files etc, but a feature request for such should be opened here
https://github.com/WardPearce/paaster-cli

**Comment by Leopere** [comment]
Yeah that was my fault I was excited about this thing.

**Comment by WardPearce** [comment]
> Yeah that was my fault I was excited about this thing.

haha fair enough, in terms of compiling. Paaster can be simply installed with pip onto anything running python 3.5+ (what is most modern linux installations.)

**Comment by Leopere** [comment]
I actually actively have to interact with things like freebsd and osx and other crap also arm and this is regularly not intermittently so it would be ideal to have little impact on the target hosts if at all possible to conceive of.  Even if it kind of becomes an insecure paste mode.

**Comment by WardPearce** [comment]
Alternative to MongoDB: [FerretDB](https://github.com/FerretDB/FerretDB) looks like a great option.
Alternative to Docker hub: [quay](https://github.com/quay/quay)

**Comment by WardPearce** [comment]
> I actually actively have to interact with things like freebsd and osx and other crap also arm and this is regularly not intermittently so it would be ideal to have little impact on the target hosts if at all possible to conceive of. Even if it kind of becomes an insecure paste mode.

Aaah yea fair, well luckily their should be of plenty of self-hosted pastebins what support curl without any encryption (maybe https://github.com/szabodanika/microbin?).

I've opened a issue on the CLI repo regarding adding piping / file support tho https://github.com/WardPearce/paaster-cli/issues/20

**Comment by WardPearce** [comment]
> thats perfect to have it be encrypted only just wish there was like a go binary rather than a pip package. Those are easier to compile and install. I'll get this installed for my own needs sooner or later and hope eternally that others see the potential and create a go one.

Yea luckily our API is documented so building custom clients shouldn't be an issue.
