### ISSUE TITLE
Minio CORs

### ISSUE THREAD

**Issue by PalmaSolutions** [WardPearce/paaster#242]
Hello, I am using self-hosted Min.io and I get the error in the title when reading a paste. I can create one, I am redirected correctly to the paste after cretion, but when I want to come back to read it again I get the above error.

I could not find a solution so far.

**Comment by WardPearce** [comment]
Hey, might be due to the downloaded content not being correct. Check the response from the S3 server for a given paste. You should do this with the network dev tools in chrome or Firefox.

**Comment by PalmaSolutions** [comment]
Thanks! Indeed, it seemed to be related with the bucket URL which did not require the port to be specified. I am still investigating it because I get a CORS error in Chrome due to the CDN being on different hostname.

**Comment by WardPearce** [comment]
> Thanks! Indeed, it seemed to be related with the bucket URL which did not require the port to be specified. I am still investigating it because I get a CORS error in Chrome due to the CDN being on different hostname.

Relevant issue relating to Minio cors https://github.com/minio/minio/issues/11111

If it is a CORs issue & you find a fix, lmk so we can document it.

**Comment by PalmaSolutions** [comment]
As per a similar issue with Docker setups just like mine it seems that they are already setting the header, but they say it is the client that is not setting it. [#https://github.com/minio/minio/issues/11258](https://github.com/minio/minio/issues/11258)
However, as per my tests this is not true. I am not seeing that header: 
![image](https://github.com/WardPearce/paaster/assets/15379026/0c7df07b-8ae1-4b02-b057-679e348471e7)
Any way I can do the requests with 'no-cors' to fetch the resource with CORS disabled?

**Comment by WardPearce** [comment]
> As per a similar issue with Docker setups just like mine it seems that they are already setting the header, but they say it is the client that is not setting it. [#https://github.com/minio/minio/issues/11258](https://github.com/minio/minio/issues/11258) However, as per my tests this is not true. I am not seeing that header: ![image](https://user-images.githubusercontent.com/15379026/260021199-0c7df07b-8ae1-4b02-b057-679e348471e7.png) Any way I can do the requests with 'no-cors' to fetch the resource with CORS disabled?

Possibly setting the CORs headers on your reverse proxy is a easy solution
