### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by kzshantonu** [WardPearce/paaster#700]
Hi,

First of all, I love this project.
I run a public instance over at https://bin.mni.li

I don't make money from it but there might be a donation link in future. 

For aesthetic reasons I prefer not to have the GitHub logo on top because on mobile it makes the header asymmetrical. Does the license allow this? My changes are on GitHub as per the license over [here](https://github.com/kzshantonu/paaster).

If disclosure of source is indeed required, is that disclosure of my changes or disclosure of the upstream?

I'll happily make any changes to comply with the license

**Comment by WardPearce** [comment]
Could you provide a screenshot how its asymmetrical?

**Comment by kzshantonu** [comment]
I know this is nitpicky but here you go:

![Screenshot_2024-11-12-17-31-44-73_e4424258c8b8649f6e67d283a50a2cbc_1](https://github.com/user-attachments/assets/7c8ae2be-6c79-41d9-9455-aabaa1955fea)

VS

![Screenshot_2024-11-12-17-31-34-58_e4424258c8b8649f6e67d283a50a2cbc_1](https://github.com/user-attachments/assets/aa996fdc-c87e-429d-a62c-eed4e66a6b58)

**Comment by WardPearce** [comment]
Aaah I see, I'd be happy for you to open a PR changing the logic of the Github icon or hiding on mobile.

**Comment by kzshantonu** [comment]
I'm not really a web dev but I'll see if I can open a PR. English is not my first language and I just wanted to know what the license allows and does not allow. Do I have to disclose my fork or the upstream? Or both? What exactly does disclosure mean? Is having my fork public on GitHub enough disclosure?

**Comment by WardPearce** [comment]
Having the source available is disclosure. As long as any of your changes are publicly available under the same licence your fine.
