### ISSUE TITLE
404 error when trying to connect

### ISSUE THREAD

**Issue by Entheologian** [WardPearce/paaster#76]
I followed the Docker steps, but when I try to connect I see this on the web browser:
{"status_code":404,"detail":"Not Found"}

And on the output:
paaster_backend | 192.168.0.100:56382 - "GET / HTTP/1.1" 404
paaster_backend | 192.168.0.100:56382 - "GET /favicon.ico HTTP/1.1" 404
paaster_backend | 192.168.0.100:33772 - "GET / HTTP/1.1" 404
paaster_backend | 192.168.0.100:33786 - "GET / HTTP/1.1" 404
paaster_backend | 192.168.0.100:33374 - "GET / HTTP/1.1" 404
[...]

Is there a step that I may have missed?

**Comment by WardPearce** [comment]
Are you trying to visit the frontend? Because you must visit the address of the frontend and not the backend if that's the case
