### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by Entheologian** [WardPearce/paaster#78]
When I type or paste something, that error dialog pops up and nothing gets pasted. I don't see any errors in the logs to hint at what the issue might be.

Might I be doing something wrong or something I missed?

**Comment by WardPearce** [comment]
Greetings, I'm assuming this is your own selfhosted version of paaster and not paaster.io? Go into the networking tab of the dev tools menu and attempt to paste in your code. This should give a more clear picture to what's going on

**Comment by WardPearce** [comment]
Feel free to provide me with the response of the HTTP request and I'll be able to help!

**Comment by Entheologian** [comment]
hmmm, in the top part (in general) I see this:

Request URL: http://localhost:8888/controller/paste/mjLXQrb-47_Z3BpsAs68hxz5fjWsCoUq
Referrer Policy: strict-origin-when-cross-origin

The console shows this:
POST http://localhost:8888/controller/paste/mjLXQrb-47_Z3BpsAs68hxz5fjWsCoUq net::ERR_BLOCKED_BY_CLIENT

My docker-compose.yml has these changes:
VITE_API_URL: "https://paaster.mydomain.com"

The default was this:
paaster_proxy_urls: '{"frontend": "http://localhost:8889", "backend": "http://localhost:8888"}'

I tried like this, thinking it may be related but no go:
paaster_proxy_urls: '{"frontend": "http://localhost:8889", "backend": "https://paaster.mydomain.com"}'

nginx is forwarding port 8888, but do I also need 8889 as well perhaps?

Thanks for the reply!

**Comment by WardPearce** [comment]
Both ports must be reversed proxied, both the frontend and backend must be publicly available.

**Comment by WardPearce** [comment]
You have a couple options, you could create a subdomain for the API or proxy mydomain.com/api to the API

**Comment by Entheologian** [comment]
So in theory, this would suffice to do that?

        location / {
                proxy_pass http://192.168.0.200:8889;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme; 
        }

        location /api {
                proxy_pass http://192.168.0.200:8888;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme; 
        }

If so, I still get the message though.

**Comment by WardPearce** [comment]
Yea you'll have to remove the route prefix from the reverse proxy, https://www.sobyte.net/post/2021-09/nginx-proxy-remove-prefixes/

or using a subdomain may be a easier solution
also /api should go before / in ur confg

**Comment by Entheologian** [comment]
I tried using the rewrite method with the upstream servers set similarly to that site and it still connects but the same issue occurs, so maybe I have the syntax incorrect. For the root one, I tried with and without the rewrite I also moved /api as you suggested.

Is this still incorrect?

```
upstream api {
        server 192.168.0.200:8888 weight=5;
}

upstream top {
        server 192.168.0.200:8889 weight=5;
}

        location ^~ /api/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;      
                rewrite ^/api/(.*)$ /$1 break;
                proxy_pass http://api;
        }

        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;      
                #rewrite ^(.*)$ /$1 break;
                proxy_pass http://top;
```

I am very new to nginx and wasn't aware of the upstream directive and the weight metrics, so this will come in handy.

**Comment by WardPearce** [comment]
Closing issue, Nginx related not to do with Paaster.
