### ISSUE TITLE
CORS Issue - Paste just spins...

### ISSUE THREAD

**Issue by mikesimps** [WardPearce/paaster#9]
Get this error when pasting in a simple string:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.paaster.io/api/settings. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Browser: Firefox 98.0.1 (64-bit)
M1 Mac Mini Monterey 12.3

![image](https://user-images.githubusercontent.com/3085186/158851289-0414540e-bc09-48b1-945d-3375a2c69757.png)

**Comment by WardPearce** [comment]
Thanks for the issue, does the same issue occur on chrome using a Mac? I use Firefox myself on Linux & the CORS seem to be respected.

**Comment by mikesimps** [comment]
No problem. Chrome works fine (Version 99.0.4844.74) but Safari does the same thing.

I actually just tried FF again and it worked! Really not sure why that would have been the case. I'll keep an eye on it and report back if I can see any sort of pattern. 

Thanks for building this!

**Comment by WardPearce** [comment]
> No problem. Chrome works fine (Version 99.0.4844.74) but Safari does the same thing.
> 
> I actually just tried FF again and it worked! Really not sure why that would have been the case. I'll keep an eye on it and report back if I can see any sort of pattern.
> 
> Thanks for building this!

Interesting, does Safari work when trying again?
Thinking it could be the CORS headers including the HTTPS protocol, `access-control-allow-origin: https://paaster.io`. Maybe i should allow https & http.

**Comment by mikesimps** [comment]
I actually tried Safari (and FF) several times before submitting the bug. Also tried it again this morning. FF still works, Safari still does not. Upon inspection, it looks like Safari may be a different issue...

![image](https://user-images.githubusercontent.com/3085186/159002896-798b06bc-fe7e-4435-ad24-07fd52d0f517.png)

**Comment by WardPearce** [comment]
> I actually tried Safari (and FF) several times before submitting the bug. Also tried it again this morning. FF still works, Safari still does not. Upon inspection, it looks like Safari may be a different issue...
> 
> ![image](https://user-images.githubusercontent.com/3085186/159002896-798b06bc-fe7e-4435-ad24-07fd52d0f517.png)

That warning isn't relevant, assuming the firefox issue was relevant to HTTP sometime. Safari might not be calling the `on:input` or `on:change` event.

**Comment by WardPearce** [comment]
Latest commit https://github.com/WardPearce/paaster/blob/Development/paaster-frontend/src/components/CreatePaste.svelte#L18
fixes Safari issues.
