### ISSUE TITLE
adding translations

### ISSUE THREAD

**Issue by samuelstroschein** [WardPearce/paaster#96]
Hi there, 

I saw your reddit post asking for translations. 

You can use https://github.com/inlang/inlang to make it easier for contributors to add translations. We can give exposure by adding paaster to the projects that use inlang, see https://inlang.com/editor. No magic bullet, but certainly makes it easier to nudge ppl to contribute translations :) 

PS I am the maintainer of inlang. If you have questions, let me know

**Comment by WardPearce** [comment]
> Hi there,
> 
> I saw your reddit post asking for translations.
> 
> You can use https://github.com/inlang/inlang to make it easier for contributors to add translations. We can give exposure by adding paaster to the projects that use inlang, see https://inlang.com/editor. No magic bullet, but certainly makes it easier to nudge ppl to contribute translations :)
> 
> PS I am the maintainer of inlang. If you have questions, let me know

Hey Sam,
Looks awesome. I'll look into adding it.
Thanks for reaching out

**Comment by WardPearce** [comment]
(Should of been done ages ago)

Completed via https://github.com/WardPearce/paaster/pull/253
